# Generated by Django 4.1 on 2022-08-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.TextField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('participacoes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('jogos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('gols_marcados', models.IntegerField()),
                ('gols_sofridos', models.IntegerField()),
                ('gols_saldo', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileirao.campeonato')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileirao.time')),
            ],
        ),
    ]
