# Generated by Django 4.1 on 2022-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasileirao', '0003_alter_time_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='ano',
            field=models.CharField(max_length=4),
        ),
    ]
